name: Build Docker Image and Push to Evolution Artifact Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CR_URI: sol-images.cr.cloud.ru
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v1
        with:
          #registry: ${{ env.CR_URI }}
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
          
      - name: NodeJS - Build and push docker image to Evolution Aritfact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
#          tags: ${{ env.CR_URI }}/landscape-planner-ui:latest #${{ github.sha }}
          tags: silviosalgari/landscape-planner-ui:latest
#          platforms: linux/amd64
#          file: Dockerfile
#          context: .
          
#      - name: Python - Build and push docker image to Evolution Aritfact Registry
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: ${{ env.CR_URI }}/evo-restapipython:${{ github.sha }}
#          file: ./restapi-python/src/Dockerfile
#          context: ./restapi-python/src

#      - name: Go - Build and push docker image to Evolution Aritfact Registry
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: ${{ env.CR_URI }}/evo-restapigo:${{ github.sha }}
#          file: ./restapi-go/src/Dockerfile
#          context: ./restapi-go/src
